"""tentativa correcao credenciais

Revision ID: f251bcbfd75d
Revises: 
Create Date: 2025-11-20 10:40:57.188097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f251bcbfd75d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacao',
    sa.Column('id_organizacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_organizacao'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('pessoa',
    sa.Column('id_pessoa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('dt_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('raca', sa.String(length=2), nullable=True),
    sa.Column('nacionalidade', sa.String(length=3), nullable=True),
    sa.Column('cns', sa.String(length=15), nullable=True),
    sa.Column('ddd', sa.String(length=2), nullable=True),
    sa.Column('telefone', sa.String(length=10), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_pessoa'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('procedimento',
    sa.Column('id_procedimento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_procedimento', sa.String(length=10), nullable=False),
    sa.Column('nome_procedimento', sa.String(length=120), nullable=False),
    sa.Column('vlr_procedimento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_procedimento'),
    sa.UniqueConstraint('cod_procedimento')
    )
    op.create_table('endereco',
    sa.Column('id_endereco', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('tipo_logradouro', sa.String(length=3), nullable=True),
    sa.Column('nome_logradouro', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ibge', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id_pessoa'], ),
    sa.PrimaryKeyConstraint('id_endereco')
    )
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id_pessoa'], ),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id_pessoa'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('acesso',
    sa.Column('id_acesso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('localizacao', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id_pessoa'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_acesso')
    )
    op.create_table('atendimento',
    sa.Column('id_atendimento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_procedimento', sa.Integer(), nullable=False),
    sa.Column('data_procedimento', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('cid', sa.String(length=4), nullable=True),
    sa.Column('carater_atendimento', sa.String(length=2), nullable=True),
    sa.Column('vlr_procedimento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id_pessoa'], ),
    sa.ForeignKeyConstraint(['id_procedimento'], ['procedimento.id_procedimento'], ),
    sa.PrimaryKeyConstraint('id_atendimento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atendimento')
    op.drop_table('acesso')
    op.drop_table('usuario')
    op.drop_table('paciente')
    op.drop_table('endereco')
    op.drop_table('procedimento')
    op.drop_table('pessoa')
    op.drop_table('organizacao')
    # ### end Alembic commands ###
